### ISSUE TITLE
Implement log panels

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydra-flock-demo#18]
* Drone log panel
* Central server log panel
* Datastream panel
* Hydra API log panel

* send message panel
* active drones

**Comment by xadahiya** [comment]
![screenshot 40](https://user-images.githubusercontent.com/9114274/28980670-58f76486-796c-11e7-82de-9fa231deb279.png)
@Mec-iS @chrizandr This design should work. Please let me know what you guys think 😄

**Comment by Mec-iS** [comment]
@xadahiya Drone Datastream should be moved on the right below Drone Log. And in the place of Drone Datastream should be placed Hydra API Log I think. So the end-user can see clearly what is happening between components.

**Comment by xadahiya** [comment]
![demo-final1](https://user-images.githubusercontent.com/9114274/28997950-64e049b6-7a3e-11e7-99f7-df4657b3fc43.gif)
@Mec-iS @chrizandr @kkoci ^^

**Comment by xadahiya** [comment]
Done
