### ISSUE TITLE
Build fails while starting the application

### ISSUE THREAD

**Issue by aribalam** [HTTP-APIs/hydra-flock-demo#38]
The following error occurs while running the `init.sh` script.

![screenshot from 2019-01-21 18-44-17](https://user-images.githubusercontent.com/20097120/51479938-bb4a3700-1db5-11e9-96bb-16b6c2ad0ea4.png)
![screenshot from 2019-01-21 18-44-22](https://user-images.githubusercontent.com/20097120/51479980-da48c900-1db5-11e9-8214-1d0dd500653e.png)

Apparently, the connection is getting closed by the server while receving a response.
The error was occurring due to the following code in `flock_controller/mechanics/location.py`    
`
update_location_ = RES_CS.find_suitable_operation(
            operation_type=SCHEMA.UpdateAction,
            input_type=CENTRAL_SERVER.Location)
`
On moving the code out of the try block, it gives the following error.
![screenshot from 2019-01-21 18-59-04](https://user-images.githubusercontent.com/20097120/51480273-a1f5ba80-1db6-11e9-8256-ba5a1f6883dd.png)

Could it be a proxy related issue as I am using a proxy network?

**Comment by vddesai1871** [comment]
>update_location_ = RES_CS.find_suitable_operation( operation_type=SCHEMA.UpdateAction, input_type=CENTRAL_SERVER.Location)

Not entirely sure but this could be the issue [comment](https://github.com/HTTP-APIs/hydrus/pull/341#issuecomment-455842919)
