### ISSUE TITLE
Build running into Errors

### ISSUE THREAD

**Issue by manki11** [HTTP-APIs/hydra-flock-demo#39]
When running the `./init.sh`, the application GUI is running on http://127.0.0.1:5000/ but nothing seems to be working and the central controller and drones are not running on thier respective ports.
<img width="1440" alt="screenshot 2019-02-14 at 7 06 28 pm" src="https://user-images.githubusercontent.com/25136650/52791199-6a64f000-308e-11e9-9c22-0452e3e6bd8f.png">
The terminal is showing the following error
<img width="1354" alt="screenshot 2019-02-14 at 7 21 56 pm" src="https://user-images.githubusercontent.com/25136650/52791225-7650b200-308e-11e9-99b0-3a7413b7b4a1.png">

**Comment by chrizandr** [comment]
You might need to re-install the requirements on a new env.

**Comment by manki11** [comment]
re-installed all the requirements still, the same error persists

**Comment by xadahiya** [comment]
It's related to greenlet, not the demo. Try googling the error.
