### ISSUE TITLE
Adapt demo to changes made in hydrus

### ISSUE THREAD

**Issue by vddesai1871** [HTTP-APIs/hydra-flock-demo#41]
Migrated from https://github.com/HTTP-APIs/hydrus/issues/374

**Comment by Mec-iS** [comment]
@invinciblycool you may be interested in this

**Comment by ba11b0y** [comment]
@vddesai1871 Were you able to get the demo running? 
controller has been bothering me.

**Comment by vddesai1871** [comment]
>@vddesai1871 Were you able to get the demo running?

No, I only ran hydra-flock-central-controller to reproduce and resolve the bug reported at https://github.com/HTTP-APIs/hydrus/issues/374

>controller has been bothering me.

It would be helpful if you can share the specific problem you are having.
