### ISSUE TITLE
Create unittest for testing from client-side

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydra-flock-demo#8]
For the moment, all the endpoints have to be tested using Python `unittest` and `requests`. For both the drone and the central server.

For example:
```
import unittest

import requests


class TestDroneRequests(unittest.TestCase):
    def test_request_vocab(self):
        r = requests.get(VOCAB_URL + '/droneapi/vocab')
        ...
       assert r.status_code == 200
```

**Comment by xadahiya** [comment]
https://github.com/HTTP-APIs/hydra-flock-demo/pull/10

**Comment by Mec-iS** [comment]
Add testing for checking that PUT and POST methods actually operate the right changes in the db

**Comment by xadahiya** [comment]
Can you explain this one a bit? What do you mean by right changes in the db?

**Comment by Mec-iS** [comment]
Test case pseudo-code:
```
request = requests.put('/some_class/<id>', some_data)
query_result = Database.get('<id>')

assert some_data == query_result
```

**Comment by xadahiya** [comment]
Implemented
